language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn global add makeshift && makeshift -s @bhp -r https://registry.npmjs.org
script:
  - yarn run build
# Identifies `a.b.c-xxx.n` tags as pre-releases, and `a.b.c` as stable releases
before_deploy: |
  - cd dist
  function npm_dist_tag() {
    if [[ "$TRAVIS_TAG" = *"-"* ]]; then
      echo "next"
    else
      echo "latest"
    fi
  }
deploy:
  provider: npm
  tag: $(npm_dist_tag)
  email: Achmad.Satriawardhana@bhp.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    all_branches: true


