language: node_js
node_js:
  - "node"
before_install:
  - npm i -g makeshift && makeshift -s @bhp -r https://registry.npmjs.org
deploy:
  provider: npm
  email: Achmad.Satriawardhana@bhp.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    branch: master
