language: node_js
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn global add makeshift && makeshift -s @bhp -r https://registry.npmjs.org
script:
  - yarn run build
before_deploy:
  - cd dist
deploy:
  provider: npm
  tag: next
  email: Achmad.Satriawardhana@bhp.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    all_branches: true


